library(chron)
library(RColorBrewer)
library(lattice)
library(ncdf4)
library(lubridate)
ncname <- "E:\\elise\\Documents\\JungoBunbo\\jan-2009-air-temperature\\ta_2m_1hr_20090101_d02.nc"
dname <- "data"  # note: tmp means temperature (not temporary)
# open a NetCDF file
ncin <- nc_open(ncname)
lon <- ncvar_get(ncin,"lon")
lat <- ncvar_get(ncin,"lat")
time <- ncvar_get(ncin,"time")
dayOfJanuary = c(1:31, 1)
time <- as.POSIXct(time*3600,origin='1970-01-01 00:00:00')
ta_2m <- ncvar_get(ncin, "ta_2m")
print(ncin)
